### ISSUE TITLE
Polybase access to Azure SQL Database in SQL Server 2019 RTM problem

### ISSUE THREAD

**Issue by ghotz** [microsoft/bobsql#10] opened 2019-12-02 14:11 UTC
I think there's a problem with the definition of an external data source from SQL Server 2019 RTM to Azure SQL Database that affect the demo in
https://github.com/microsoft/bobsql/tree/master/demos/sqlserver/polybase/sqldatahub/azuredb

The problem is the one I opened with the documentation here:
https://github.com/MicrosoftDocs/sql-docs/issues/3727

In short: it looks like unless you specify the database name in `CONNECTION_OPTIONS` when creating an external data source to Azure SQL Database with `CREATE EXTERNAL DATA SOURCE`, you get ODBC error `Database is invalid or cannot be accessed`.

I'm not changing the example scripts because it may be a regression in 2019 RTM...

**Comment by rgward** [comment] 2019-12-02 15:12
Thanks for this report. I'll look into it

**Comment by rgward** [comment] 2019-12-03 00:21
I don't see this problem even using the SQL Server 2019 RTM build. I used the exact same script as I have on GitHub and it works just fine. Can you post the details of the T-SQL script you used that failed?

**Comment by rgward** [comment] 2019-12-03 03:44
I'm looking at this again because on a different server I got the same error you did

**Comment by rgward** [comment] 2019-12-03 04:03
ok, my testing shows this problem is happening with SQL 2019 RTM but appears to be fixed in with our GDR servicing update. Can you apply this and see if the problem is fixed? https://support.microsoft.com/en-us/help/4517790/servicing-update-for-sql-server-2019-rtm

**Comment by rgward** [comment] 2019-12-03 15:50
I confirmed there was a bug regression that is fixed in the GDR build. We are looking how best to document this.

**Closed by rgward** 2019-12-03 15:50 UTC
